# Generated by Django 4.2.1 on 2023-07-03 06:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_app', '0001_initial'),
        ('ticket_app', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('bank_name', models.CharField(blank=True, max_length=20)),
                ('bank_code', models.CharField(max_length=67)),
                ('account_name', models.CharField(blank=True, max_length=50)),
                ('recipient_code', models.CharField(blank=True, max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawEventEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=24)),
                ('bank_detail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payments.bankdetail')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='event_app.eventinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('user', models.EmailField(max_length=254)),
                ('quantity', models.IntegerField()),
                ('paystack_reference', models.CharField(blank=True, max_length=65)),
                ('amount', models.IntegerField(blank=True)),
                ('status', models.CharField(blank=True, max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='checkouts', to='ticket_app.ticket')),
            ],
        ),
    ]
