# Generated by Django 4.2.1 on 2023-05-12 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_organization_creator"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_number", models.IntegerField()),
                ("bank_name", models.CharField(max_length=20)),
                ("bank_code", models.IntegerField()),
                ("account_name", models.CharField(max_length=50)),
                ("receipient_code", models.IntegerField(null=True)),
                (
                    "owner",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
    ]
