# Generated by Django 4.2.1 on 2023-05-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="status",
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
