# Generated by Django 4.2.1 on 2023-05-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_checkout_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="amount",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="checkout",
            name="paystack_reference",
            field=models.CharField(blank=True, max_length=65),
        ),
        migrations.AlterField(
            model_name="checkout",
            name="status",
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
