# Generated by Django 4.2.1 on 2023-07-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_checkout_id_alter_checkout_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='uuid',
            new_name='id',
        ),
    ]
