# Generated by Django 4.2.1 on 2023-05-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_bankdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankdetail",
            name="bank_name",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
