# Generated by Django 4.2.1 on 2023-05-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_bankdetail_bank_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankdetail",
            name="bank_name",
            field=models.CharField(blank=True, default=1, max_length=20),
            preserve_default=False,
        ),
    ]
