# Generated by Django 4.2.1 on 2023-05-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_bankdetail_bank_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankdetail",
            name="account_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
