# Generated by Django 4.2.1 on 2023-05-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_bankdetail_account_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bankdetail",
            name="receipient_code",
        ),
        migrations.AddField(
            model_name="bankdetail",
            name="recipient_code",
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
