# Generated by Django 4.2.1 on 2023-05-12 23:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("event_app", "0001_initial"),
        ("payments", "0007_withdrawticketearnings"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawEventEarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference_code", models.UUIDField(verbose_name=uuid.uuid4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="Pending", max_length=24)),
                (
                    "bank_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="payments.bankdetail",
                    ),
                ),
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event_app.eventinfo",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="WithdrawTicketEarnings",
        ),
    ]
