# Generated by Django 4.2.1 on 2023-05-13 00:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_withdraweventearning_delete_withdrawticketearnings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdraweventearning",
            name="reference_code",
            field=models.UUIDField(blank=True, verbose_name=uuid.uuid4),
        ),
    ]
