# Generated by Django 4.2.1 on 2023-05-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_listofbank_alter_bankdetail_bank_code"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ListOfBank",
        ),
        migrations.AlterField(
            model_name="bankdetail",
            name="bank_code",
            field=models.CharField(max_length=67),
        ),
    ]
