# Generated by Django 4.2.1 on 2023-07-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
    ]
