# Generated by Django 4.2.1 on 2023-07-05 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_organization_id_alter_organization_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='uuid',
            new_name='id',
        ),
    ]
