# Generated by Django 4.2.1 on 2023-07-02 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20230702_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(auto_created=True, max_length=56, primary_key=True, serialize=False),
        ),
    ]
