# Generated by Django 4.2.1 on 2023-07-03 02:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_uuid_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=34),
        ),
    ]
