# Generated by Django 4.2.1 on 2023-05-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventinfo",
            name="artwork",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
