# Generated by Django 4.2.1 on 2023-05-13 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventinfo",
            name="earnings",
            field=models.IntegerField(default=2500),
            preserve_default=False,
        ),
    ]
