# Generated by Django 4.2.1 on 2023-05-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_app", "0002_alter_user_managers_remove_user_username_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["date_joined"]},
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default=1, max_length=67),
            preserve_default=False,
        ),
    ]
