# Generated by Django 4.2.1 on 2023-05-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventinfo",
            name="end_date",
            field=models.DateField(null=True),
        ),
    ]
