# Generated by Django 4.2.1 on 2023-06-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0004_eventinfo_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinfo',
            name='type',
            field=models.CharField(choices=[('Paid', 'paid'), ('Free', 'free')], default=1, max_length=40),
            preserve_default=False,
        ),
    ]
