# Generated by Django 4.2.1 on 2023-06-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0005_eventinfo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='type',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Free', 'Free')], max_length=40),
        ),
    ]
