# Generated by Django 4.2.1 on 2023-05-07 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("event_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="Regular", max_length=34)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("price", models.IntegerField()),
                ("available_tickets", models.IntegerField()),
                ("start_time", models.TimeField()),
                ("start_date", models.DateField()),
                ("end_time", models.TimeField()),
                ("end_date", models.DateField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="event_app.eventinfo",
                    ),
                ),
            ],
        ),
    ]
