# Generated by Django 4.2.1 on 2023-07-02 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('status', models.CharField(default='Regular', max_length=34)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('available_tickets', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_time', models.TimeField()),
                ('end_date', models.DateField()),
                ('total_checkout_amount', models.IntegerField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tickets', to='event_app.eventinfo')),
            ],
        ),
    ]
