# Generated by Django 4.2.1 on 2023-05-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="total_checkout_amount",
            field=models.IntegerField(null=True),
        ),
    ]
