# Generated by Django 4.2.1 on 2023-05-08 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("event_app", "0002_alter_eventinfo_artwork"),
        ("ticket_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="tickets",
                to="event_app.eventinfo",
            ),
        ),
    ]
